# Generated by Django 5.2.5 on 2025-08-23 12:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0002_image_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='title',
        ),
    ]
